### ISSUE TITLE
Benchexec expects DONE in output

### ISSUE THREAD

**Issue by rafaelsamenezes** [kaled-alshmrany/FuSeBMC#1]
The Wrapper is returning FAIL_COVER_ERROR_CALL or FAIL_COVER_BRANCHES. It should be DONE

Relevant files:

- Wrapper: https://github.com/kaled-alshmrany/FuSeBMC/blob/master/my_wrapper/my_esbmc_wrapper_final_001.py#L663-L667

Explanation:

Benchexec integrates with each tool with a custom module, ESBMC's module is [here](https://github.com/sosy-lab/benchexec/blob/master/benchexec/tools/esbmc.py#L39-L58), last years competition it was decided that when the tool finished it should output a DONE result in TestComp.

**Comment by kaled-alshmrany** [comment]
Now, it is returning DONE
