### ISSUE TITLE
Remove hardcoded paths

### ISSUE THREAD

**Issue by rafaelsamenezes** [kaled-alshmrany/FuSeBMC#2]
There are some hardcoded paths in the wrapper. The wrapper should rely on PATH to get the binaries.

Example: https://github.com/kaled-alshmrany/FuSeBMC/blob/master/my_wrapper/my_esbmc_wrapper_final_001.py#L33

Just remove all of them.

**Comment by kaled-alshmrany** [comment]
102c16882802408aa4ac03e9f226319cf8b7eb61
f9ace0c9d63af8c52e2a42a8698e05873dfadc13
1506c5c71f63de81356e98ec0a1e10592026c8fd
