### ISSUE TITLE
Add a recipe in Makefile to generate the release

### ISSUE THREAD

**Issue by rafaelsamenezes** [kaled-alshmrany/FuSeBMC#3]
In TestComp we will need to generate a release to be used by external environments so we could use something like `make release`, it should:

- Be static
- Contain the wrapper (named as esbmc-wrapper.py), esbmc, and the instrumentation tool.

If it generated something like `fusebmc.tar.gz` it would be great.

**Comment by kaled-alshmrany** [comment]
c5a3500221bbf643c10b6ff58bbe85a6b5dd991c
