### ISSUE TITLE
Create output directory if needed in my_instrument

### ISSUE THREAD

**Issue by rafaelsamenezes** [kaled-alshmrany/FuSeBMC#5]
Running `./my_instrument --input  test.c --output ./my_instrument_outpt/instrumrnted.c --goal-output-file ./my_instrument_outpt/goals.txt --add-else --add-labels` throws an error if the output directory does not exist.

**Comment by kaled-alshmrany** [comment]
02ac38120a1e2ade2f04b4e35cc6d3f7d441abca

**Comment by kaled-alshmrany** [comment]
start from line 127
