### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by thalestas** [kaled-alshmrany/FuSeBMC#7]
I tried to compile but the following issue occurred.

```
make clean release
rm -f obj/*.o
rm -f FuSeBMC_inustrment
/home/kaled/Downloads/clang_base/bin/clang++ -Wall -Wextra -W -std=c++11 -I./include -I/home/kaled/Downloads/clang_base/include -I/mnt/sda2/llvm-6.0.0/include  -fno-rtti  -Wno-unsequenced -Wno-unused-parameter -o3 -os  -c src/GoalCounter.cpp -o obj/GoalCounter.o
make: /home/kaled/Downloads/clang_base/bin/clang++: No such file or directory
make: *** [Makefile:26: obj/GoalCounter.o] Error 127
```
Checking the Makefile the CLANG_BASE is hardcoded:

```
 CLANG_BASE = /home/kaled/Downloads/clang_base  
```

**Comment by kaled-alshmrany** [comment]
First, many thanks for your interest. Regarding the issue, yeah, you are right; I haven't updated it yet. Anyway, you can try the latest version of FuSeBMC v4.1.14 from this link it should work well: 

https://gitlab.com/sosy-lab/test-comp/archives-2022/-/raw/main/2022/FuSeBMC.zip?inline=false

**Comment by thalestas** [comment]
Thanks! 
I'm gonna to try!

**Comment by kaled-alshmrany** [comment]
I have updated the README file, which now refers to the correct file. Please let me know if everything is all right so we can close the issue.

**Comment by thalestas** [comment]
Hi @kaled-alshmrany, it worked well.
Thanks.
