### ISSUE TITLE
Adding compiler flags to the instrumented code 

### ISSUE THREAD

**Issue by omkarbhat1995** [kaled-alshmrany/FuSeBMC#8]
While compiling instrumented code, is there a way to pass compiler flags to it without hardcoding it in the fusebmc.py. 
Also I'm getting lstFuSeBMC_GoalTracerGoals=[] and lstFuSeBMC_FuzzerGoals_Run2=[] but I think that's because fusebmc cant compile the instrumented code as it has a set of flags that are not being set.

**Comment by kaled-alshmrany** [comment]
I would say, you could try to use the new version (FuSeBMC-AI).
