### ISSUE TITLE
Broken download link in README

### ISSUE THREAD

**Issue by fbrausse** [kaled-alshmrany/FuSeBMC#9]
The download link to ESBMC in the README is no longer available as that project changed its build infrastructure. Could you instead please point to the esbmc-linux.zip, e.g. https://github.com/esbmc/esbmc/releases/download/v7.5/esbmc-linux.zip for v7.5 (in case you want to update it from v7.4).

**Comment by kaled-alshmrany** [comment]
Many thanks @fbrausse ; I have updated the README with the new link of ESBMC.
